plots:
	gnuplot 1_to_n_ot.plt
	gnuplot 1_to_n_ot_throughput.plt
	gnuplot 1_to_n_ot_chou_orlandi_based.plt
	gnuplot 1_to_n_ot_chou_orlandi_based_throughput.plt
	gnuplot fpake.plt
	gnuplot fpake_throughput.plt
	gnuplot fpake_hamming_distance.plt
	gnuplot fpake_hamming_distance_throughput.plt
	gnuplot garbled_circuits.plt
	gnuplot garbled_circuits_throughput.plt
	gnuplot garbled_circuits_evaluate.plt
	gnuplot garbled_circuits_evaluate_throughput.plt
	gnuplot garbled_circuits_garble.plt
	gnuplot garbled_circuits_garble_throughput.plt
	gnuplot one_of_many_fpake.plt
	gnuplot one_of_many_mfpake_comparison.plt
	gnuplot one_of_many_fpake_throughput.plt
	gnuplot one_of_many_fpake_mfpake.plt
	gnuplot one_of_many_fpake_mfpake_throughput.plt
	gnuplot one_of_many_fpake_mfpake_hd.plt
	gnuplot one_of_many_fpake_mfpake_hd_comparison.plt
	gnuplot one_of_many_fpake_mfpake_hd_throughput.plt
	gnuplot one_of_many_fpake_v1_v1.plt
	gnuplot one_of_many_fpake_v1_v1_throughput.plt
	gnuplot one_of_many_fpake_v2_v2.plt
	gnuplot one_of_many_fpake_v2_v2_throughput.plt
	gnuplot ot.plt
	gnuplot ot_throughput.plt
	gnuplot ot_apricot.plt
	gnuplot ot_apricot_throughput.plt
	gnuplot ot_apricot_classic.plt
	gnuplot ot_apricot_classic_throughput.plt
	gnuplot ot_chou_orlandi.plt
	gnuplot ot_chou_orlandi_throughput.plt
	gnuplot polynomial_multiply_reduce.plt
	gnuplot polynomial_multiply_reduce_throughput.plt
	gnuplot polynomial_multiply_reduce_generic_implementation.plt
	gnuplot polynomial_multiply_reduce_generic_implementation_throughput.plt
	gnuplot polynomial_multiply_reduce_x86_implementation.plt
	gnuplot polynomial_multiply_reduce_x86_implementation_throughput.plt

clean:
	rm -rf *.plt
	rm -rf data/*.dat
	rm -rf out/*.pdf
	rm -rf out/*.tex
